quarkus:
  http:
    cors:
      origins: "${CORS_ORIGINS}"
  oidc:
    auth-server-url: "${OIDC_AUTH_SERVER_URL}"
    client-id: "${OIDC_CLIENT_ID}"
    token:
      audience: "${OIDC_TOKEN_AUDIENCE}"
      issuer: "${OIDC_TOKEN_ISSUER}"
  datasource:
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    jdbc:
      url: "${DB_JDBC_URL}"
      min-size: "${DB_JDBC_MIN_SIZE:1}"
      max-size: "${DB_JDBC_MAX_SIZE:8}"
    reactive:
      url: "${DB_REACTIVE_URL}"
      max-size: "${DB_POOL_MAX_SIZE:60}"
      hostname-verification-algorithm: "${DB_REACTIVE_HOSTNAME_VERIFICATION_ALGORITHM:HTTPS}"
      postgresql:
        ssl-mode: "${DB_REACTIVE_SSL_MODE:verify-full}"
      trust-certificate-pem:
        ~: true
        certs: "${DB_REACTIVE_TRUST_CERTIFICATE_PATH:/tmp/certificates/aws-rds-ca-bundle.pem}"
  mailer:
    from: "${MAIL_FROM}"
    host: "${MAIL_HOST}"
    port: "${MAIL_PORT}"
    start-tls: "${MAIL_START_TLS:REQUIRED}"
    login: "${MAIL_LOGIN:REQUIRED}"
    auth-methods: "${MAIL_AUTH_METHODS:PLAIN LOGIN}"

app:
  fusionauth:
    base-url: "${FUSIONAUTH_BASE_URL}"
    api-key: "${FUSIONAUTH_API_KEY}"
    application-id: "${FUSIONAUTH_APPLICATION_ID}"
    tenant-id: "${FUSIONAUTH_TENANT_ID:30663132-6464-6665-3032-326466613934}"
  public-base-url: "${PUBLIC_BASE_URL}"
  email-assets:
    base-url: "${EMAIL_ASSETS_BASE_URL}"
  mail:
    ses:
      configuration-set: "${MAIL_SES_CONFIGURATION_SET:}"
  security:
    owner-email: "${OWNER_EMAIL}"
    bootstrap-owner: "${OWNER_BOOTSTRAP:false}"
